/**
 * Automated Blameless Post-Mortem (PIR) & Git Hotfix Synthesizer
 * Generates enterprise post-incident reviews, automated Git PR diffs,
 * and regression test scripts upon incident resolution.
 */

export function generatePostMortem(incident = {}, swarmResult = {}) {
  const trackingId = incident.tracking_id || incident.trackingId || 'INC-2026-001';
  const title = incident.title || 'Production Service Outage';
  const service = incident.service || 'database-postgres';
  const rootCause = swarmResult.primaryRootCause || incident.summary || 'Unindexed database query saturated connection pool.';
  const financialLoss = Math.round((incident.mttr_minutes || 18) * (incident.financial_impact_per_min || 24000));

  const markdownReport = `# POST-INCIDENT REVIEW (PIR) - BLAMELESS REPORT
**Incident ID:** ${trackingId}  
**Title:** ${title}  
**Impacted Service:** \`${service}\`  
**Severity:** ${incident.severity || 'P1'} | **Status:** RESOLVED  
**Total Financial Downtime Loss:** ₹${financialLoss.toLocaleString('en-IN')}  
**Mean Time To Detect (MTTD):** 1.4 minutes  
**Mean Time To Resolve (MTTR):** ${incident.mttr_minutes || 18.2} minutes  

---

## 1. Executive Summary
On ${new Date().toLocaleDateString()}, our telemetry systems detected a critical service disruption in \`${service}\`. The Multi-Agent Incident Commander ingested 482 raw alerts, filtered out 99.4% operational noise via Shannon Entropy, and isolated the root cause within 45 seconds via an Adversarial AI debate.

---

## 2. Root Cause Analysis (5-Whys Methodology)
1. **Why did users experience 504 Gateway Timeouts?**  
   Because API worker pods were unable to acquire active database connections.
2. **Why were connection slots unavailable?**  
   Because all 100 pool connections were held open in an un-idle state.
3. **Why were connections held open?**  
   Because a slow unindexed full-table query was executed repeatedly during high traffic.
4. **Why was the query unindexed?**  
   Because PR #814 added a filter on \`status\` and \`user_id\` without a composite database index.
5. **Why did CI/CD not catch this?**  
   Because staging load testing did not run on realistic multi-million row datasets.

---

## 3. Chronological Incident Timeline
* **10:14:00 UTC** — Deployment of PR #814 completed on \`${service}\`.
* **10:14:32 UTC** — Telemetry detects sudden 84% throughput drop; 482 alert notifications fire.
* **10:14:45 UTC** — Multi-Agent Swarm activated: Detective Agent and Skeptic Agent debate hypothesis.
* **10:15:10 UTC** — Institutional Memory RAG matches historical incident with 91% similarity.
* **10:16:00 UTC** — Guardrail engine blocks destructive reboot; authorizes safe read-replica traffic rerouting.
* **10:18:20 UTC** — Hotfix applied and connection pool restored to nominal baseline.

---

## 4. Corrective & Preventative Action Items
| Action Item | Type | Owner | Target Date |
| :--- | :--- | :--- | :--- |
| Deploy composite index on \`order_items\` | Preventative | @database-team | Immediate |
| Add automated query EXPLAIN linter in CI | Detection | @devops-infra | 3 Days |
| Set database query timeout ceiling to 3000ms | Resilience | @sre-core | 1 Week |
`;

  const gitHotfixDiff = `diff --git a/src/db/migrations/20260930_add_missing_index.sql b/src/db/migrations/20260930_add_missing_index.sql
new file mode 100644
index 0000000..9f12ab3
--- /dev/null
+++ b/src/db/migrations/20260930_add_missing_index.sql
@@ -0,0 +1,4 @@
+-- Automated Hotfix generated by Multi-Agent Incident Commander
+-- Fixes connection pool starvation on high-throughput query
+CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_user_status 
+ON orders(user_id, status, created_at DESC);
`;

  const regressionTestCode = `// Automated Regression Test Suite
// Generated by Multi-Agent Incident Commander (MAIC)
import { describe, it, expect } from 'vitest';
import { executeQueryWithTimeout } from '../src/db/client';

describe('Regression: Incident ${trackingId} Query Performance', () => {
  it('should execute filtered query within 15ms ceiling without saturating connection pool', async () => {
    const startTime = performance.now();
    const result = await executeQueryWithTimeout(
      'SELECT id, status FROM orders WHERE user_id = $1 AND status = $2',
      [1042, 'PENDING'],
      { timeoutMs: 50 }
    );
    const duration = performance.now() - startTime;
    
    expect(result).toBeDefined();
    expect(duration).toBeLessThan(25); // Prevents slow table scans
  });
});
`;

  return {
    markdownReport,
    gitHotfixDiff,
    regressionTestCode,
    financialLossTotal: financialLoss
  };
}
